#pragma once

// -- Enum -- //

enum class WARP_RESULT_ENUM
{
	   OK		= 0
	,  FAIL		
	,  NOT_FOUND_GRAPHIC
	,  FAIL_QUERY_INTERFACE
	,  FAIL_CREATE_SWAP_CHAIN
	,  FAIL_CREATE_DXGI_FACTORY_
	,  FAIL_GET_BUFFER
	,  FAIL_CREATE_RTV
	,  FAIL_CREATE_RS
	,  FAIL_CREATE_BS // Bleand States
	,  FAIL_CREATE_DSV
	,  FAIL_CREATE_TXT2D
	,  FAIL_CREATE_VS
	,  FAIL_CREATE_HS
	,  FAIL_CREATE_DS
	,  FAIL_CREATE_GS
	,  FAIL_CREATE_PS
	,  FAIL_LATE_START 
};

